import 'package:flutter/material.dart';

enum DayPilotTheme { sageGreen, ocean, lavender, amber, amoled }

final dayPilotThemeNotifier = ValueNotifier<DayPilotTheme>(DayPilotTheme.sageGreen);

final dayPilotThemeModeNotifier = ValueNotifier<ThemeMode>(ThemeMode.system);

ThemeData buildTheme(DayPilotTheme theme, {bool darkMode = false}) {
  return switch (theme) {
    DayPilotTheme.sageGreen => _build(_sageLight, _sageDark, darkMode,
        const Color(0xFFF4F9F5), const Color(0xFF0E1F13)),
    DayPilotTheme.ocean => _build(_oceanLight, _oceanDark, darkMode,
        const Color(0xFFF2F8FB), const Color(0xFF001F2A)),
    DayPilotTheme.lavender => _build(_lavLight, _lavDark, darkMode,
        const Color(0xFFF7F4FC), const Color(0xFF100A20)),
    DayPilotTheme.amber => _build(_amberLight, _amberDark, darkMode,
        const Color(0xFFFFF8F2), const Color(0xFF1F0E00)),
    DayPilotTheme.amoled => _amoledTheme(),
  };
}

ThemeData _build(ColorScheme light, ColorScheme dark, bool darkMode,
    Color bgLight, Color bgDark) {
  final cs = darkMode ? dark : light;
  return ThemeData(
    useMaterial3: true,
    colorScheme: cs,
    scaffoldBackgroundColor: darkMode ? bgDark : bgLight,
  );
}

// error/shadow/scrim never varied per accent theme to begin with — Material's
// semantic error red and pure-black shadow/scrim are the same regardless of theme.
const _lightError = (
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
);

const _darkError = (
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
);

// Bundles the ~26 fields that actually vary per theme into one value so
// _scheme() doesn't need a parameter per field (Sonar flagged 28 params).
typedef _SchemeColors = ({
  Color primary,
  Color onPrimary,
  Color primaryContainer,
  Color onPrimaryContainer,
  Color secondary,
  Color onSecondary,
  Color secondaryContainer,
  Color onSecondaryContainer,
  Color tertiary,
  Color onTertiary,
  Color tertiaryContainer,
  Color onTertiaryContainer,
  Color surface,
  Color onSurface,
  Color surfaceContainerLowest,
  Color surfaceContainerLow,
  Color surfaceContainer,
  Color surfaceContainerHigh,
  Color surfaceContainerHighest,
  Color onSurfaceVariant,
  Color outline,
  Color outlineVariant,
  Color inverseSurface,
  Color onInverseSurface,
  Color inversePrimary,
  Color surfaceTint,
});

ColorScheme _scheme(
  Brightness brightness,
  _SchemeColors c, {
  ({Color error, Color onError, Color errorContainer, Color onErrorContainer})? errorColors,
}) {
  errorColors ??= brightness == Brightness.light ? _lightError : _darkError;
  return ColorScheme(
    brightness: brightness,
    primary: c.primary,
    onPrimary: c.onPrimary,
    primaryContainer: c.primaryContainer,
    onPrimaryContainer: c.onPrimaryContainer,
    secondary: c.secondary,
    onSecondary: c.onSecondary,
    secondaryContainer: c.secondaryContainer,
    onSecondaryContainer: c.onSecondaryContainer,
    tertiary: c.tertiary,
    onTertiary: c.onTertiary,
    tertiaryContainer: c.tertiaryContainer,
    onTertiaryContainer: c.onTertiaryContainer,
    error: errorColors.error,
    onError: errorColors.onError,
    errorContainer: errorColors.errorContainer,
    onErrorContainer: errorColors.onErrorContainer,
    surface: c.surface,
    onSurface: c.onSurface,
    surfaceContainerLowest: c.surfaceContainerLowest,
    surfaceContainerLow: c.surfaceContainerLow,
    surfaceContainer: c.surfaceContainer,
    surfaceContainerHigh: c.surfaceContainerHigh,
    surfaceContainerHighest: c.surfaceContainerHighest,
    onSurfaceVariant: c.onSurfaceVariant,
    outline: c.outline,
    outlineVariant: c.outlineVariant,
    shadow: Colors.black,
    scrim: Colors.black,
    inverseSurface: c.inverseSurface,
    onInverseSurface: c.onInverseSurface,
    inversePrimary: c.inversePrimary,
    surfaceTint: c.surfaceTint,
  );
}

final _sageLight = _scheme(
  Brightness.light,
  (
    primary: const Color(0xFF4A7C59),
    onPrimary: const Color(0xFFFFFFFF),
    primaryContainer: const Color(0xFFB7DFBD),
    onPrimaryContainer: const Color(0xFF002111),
    secondary: const Color(0xFF81A88D),
    onSecondary: const Color(0xFFFFFFFF),
    secondaryContainer: const Color(0xFFE8F2EB),
    onSecondaryContainer: const Color(0xFF1A2E1F),
    tertiary: const Color(0xFF5C8A6A),
    onTertiary: const Color(0xFFFFFFFF),
    tertiaryContainer: const Color(0xFFA8C5A0),
    onTertiaryContainer: const Color(0xFF1A3320),
    surface: const Color(0xFFFFFFFF),
    onSurface: const Color(0xFF1A2E1F),
    surfaceContainerLowest: const Color(0xFFFFFFFF),
    surfaceContainerLow: const Color(0xFFF4F9F5),
    surfaceContainer: const Color(0xFFEEF5EF),
    surfaceContainerHigh: const Color(0xFFEBF3EC),
    surfaceContainerHighest: const Color(0xFFE8F2EB),
    onSurfaceVariant: const Color(0xFF3D5C45),
    outline: const Color(0xFF6B9474),
    outlineVariant: const Color(0xFFB0CCB5),
    inverseSurface: const Color(0xFF2E3B31),
    onInverseSurface: const Color(0xFFF0F5F0),
    inversePrimary: const Color(0xFF7EBD8F),
    surfaceTint: const Color(0xFF4A7C59),
  ),
);

final _sageDark = _scheme(
  Brightness.dark,
  (
    primary: const Color(0xFF7EBD8F),
    onPrimary: const Color(0xFF0E3320),
    primaryContainer: const Color(0xFF2E5E40),
    onPrimaryContainer: const Color(0xFF93D0A1),
    secondary: const Color(0xFF9DBFA8),
    onSecondary: const Color(0xFF1A3325),
    secondaryContainer: const Color(0xFF243B29),
    onSecondaryContainer: const Color(0xFFB8D4BF),
    tertiary: const Color(0xFF7EBD8F),
    onTertiary: const Color(0xFF0E3320),
    tertiaryContainer: const Color(0xFF1A3325),
    onTertiaryContainer: const Color(0xFF93D0A1),
    surface: const Color(0xFF1A2E1F),
    onSurface: const Color(0xFFD4EDDA),
    surfaceContainerLowest: const Color(0xFF0E1F13),
    surfaceContainerLow: const Color(0xFF1A2E1F),
    surfaceContainer: const Color(0xFF1E3323),
    surfaceContainerHigh: const Color(0xFF243B29),
    surfaceContainerHighest: const Color(0xFF2E4733),
    onSurfaceVariant: const Color(0xFF9DBFA8),
    outline: const Color(0xFF5C8A6A),
    outlineVariant: const Color(0xFF2E5E40),
    inverseSurface: const Color(0xFFD4EDDA),
    onInverseSurface: const Color(0xFF1A2E1F),
    inversePrimary: const Color(0xFF4A7C59),
    surfaceTint: const Color(0xFF7EBD8F),
  ),
);

final _oceanLight = _scheme(
  Brightness.light,
  (
    primary: const Color(0xFF1A6B8A),
    onPrimary: const Color(0xFFFFFFFF),
    primaryContainer: const Color(0xFFB3E3F5),
    onPrimaryContainer: const Color(0xFF001F2A),
    secondary: const Color(0xFF4A9BB5),
    onSecondary: const Color(0xFFFFFFFF),
    secondaryContainer: const Color(0xFFE0F2F8),
    onSecondaryContainer: const Color(0xFF001F2A),
    tertiary: const Color(0xFF2E7A96),
    onTertiary: const Color(0xFFFFFFFF),
    tertiaryContainer: const Color(0xFF80C4D8),
    onTertiaryContainer: const Color(0xFF002B38),
    surface: const Color(0xFFFFFFFF),
    onSurface: const Color(0xFF001F2A),
    surfaceContainerLowest: const Color(0xFFFFFFFF),
    surfaceContainerLow: const Color(0xFFF2F8FB),
    surfaceContainer: const Color(0xFFEAF4F8),
    surfaceContainerHigh: const Color(0xFFE4F0F6),
    surfaceContainerHighest: const Color(0xFFE0F2F8),
    onSurfaceVariant: const Color(0xFF1A4D5E),
    outline: const Color(0xFF4A8BA0),
    outlineVariant: const Color(0xFFB0D8E8),
    inverseSurface: const Color(0xFF002B38),
    onInverseSurface: const Color(0xFFE8F5FB),
    inversePrimary: const Color(0xFF5BC8E8),
    surfaceTint: const Color(0xFF1A6B8A),
  ),
);

final _oceanDark = _scheme(
  Brightness.dark,
  (
    primary: const Color(0xFF5BC8E8),
    onPrimary: const Color(0xFF003547),
    primaryContainer: const Color(0xFF1A6B8A),
    onPrimaryContainer: const Color(0xFFB3E3F5),
    secondary: const Color(0xFF80C4D8),
    onSecondary: const Color(0xFF003547),
    secondaryContainer: const Color(0xFF0D3D4F),
    onSecondaryContainer: const Color(0xFFCCEAF5),
    tertiary: const Color(0xFF5BC8E8),
    onTertiary: const Color(0xFF003547),
    tertiaryContainer: const Color(0xFF0D3D4F),
    onTertiaryContainer: const Color(0xFFB3E3F5),
    surface: const Color(0xFF002B38),
    onSurface: const Color(0xFFCCEAF5),
    surfaceContainerLowest: const Color(0xFF001F2A),
    surfaceContainerLow: const Color(0xFF002B38),
    surfaceContainer: const Color(0xFF08303F),
    surfaceContainerHigh: const Color(0xFF0D3D4F),
    surfaceContainerHighest: const Color(0xFF12465A),
    onSurfaceVariant: const Color(0xFF80C4D8),
    outline: const Color(0xFF2E7A96),
    outlineVariant: const Color(0xFF0D4F6B),
    inverseSurface: const Color(0xFFCCEAF5),
    onInverseSurface: const Color(0xFF002B38),
    inversePrimary: const Color(0xFF1A6B8A),
    surfaceTint: const Color(0xFF5BC8E8),
  ),
);

final _lavLight = _scheme(
  Brightness.light,
  (
    primary: const Color(0xFF6B4FA8),
    onPrimary: const Color(0xFFFFFFFF),
    primaryContainer: const Color(0xFFE4D7FF),
    onPrimaryContainer: const Color(0xFF1A1030),
    secondary: const Color(0xFF9B7FCC),
    onSecondary: const Color(0xFFFFFFFF),
    secondaryContainer: const Color(0xFFEDE8F8),
    onSecondaryContainer: const Color(0xFF1A1030),
    tertiary: const Color(0xFF7A5EAD),
    onTertiary: const Color(0xFFFFFFFF),
    tertiaryContainer: const Color(0xFFC4AAEE),
    onTertiaryContainer: const Color(0xFF1E0A40),
    surface: const Color(0xFFFFFFFF),
    onSurface: const Color(0xFF1A1030),
    surfaceContainerLowest: const Color(0xFFFFFFFF),
    surfaceContainerLow: const Color(0xFFF7F4FC),
    surfaceContainer: const Color(0xFFF2EEF9),
    surfaceContainerHigh: const Color(0xFFEFE9F6),
    surfaceContainerHighest: const Color(0xFFEDE8F8),
    onSurfaceVariant: const Color(0xFF4D338A),
    outline: const Color(0xFF7A5EAD),
    outlineVariant: const Color(0xFFCFC0F0),
    inverseSurface: const Color(0xFF261A40),
    onInverseSurface: const Color(0xFFF0EBF8),
    inversePrimary: const Color(0xFFBCA0E8),
    surfaceTint: const Color(0xFF6B4FA8),
  ),
);

final _lavDark = _scheme(
  Brightness.dark,
  (
    primary: const Color(0xFFBCA0E8),
    onPrimary: const Color(0xFF2B1060),
    primaryContainer: const Color(0xFF4D338A),
    onPrimaryContainer: const Color(0xFFE4D7FF),
    secondary: const Color(0xFFCDB8F0),
    onSecondary: const Color(0xFF2B1060),
    secondaryContainer: const Color(0xFF261A40),
    onSecondaryContainer: const Color(0xFFE8DCFF),
    tertiary: const Color(0xFFBCA0E8),
    onTertiary: const Color(0xFF2B1060),
    tertiaryContainer: const Color(0xFF261A40),
    onTertiaryContainer: const Color(0xFFE4D7FF),
    surface: const Color(0xFF1A1030),
    onSurface: const Color(0xFFE8DCFF),
    surfaceContainerLowest: const Color(0xFF100A20),
    surfaceContainerLow: const Color(0xFF1A1030),
    surfaceContainer: const Color(0xFF1F1438),
    surfaceContainerHigh: const Color(0xFF261A40),
    surfaceContainerHighest: const Color(0xFF2E2050),
    onSurfaceVariant: const Color(0xFFCDB8F0),
    outline: const Color(0xFF7A5EAD),
    outlineVariant: const Color(0xFF4D338A),
    inverseSurface: const Color(0xFFE8DCFF),
    onInverseSurface: const Color(0xFF1A1030),
    inversePrimary: const Color(0xFF6B4FA8),
    surfaceTint: const Color(0xFFBCA0E8),
  ),
);

final _amberLight = _scheme(
  Brightness.light,
  (
    primary: const Color(0xFFB85C00),
    onPrimary: const Color(0xFFFFFFFF),
    primaryContainer: const Color(0xFFFFDCB4),
    onPrimaryContainer: const Color(0xFF2E1500),
    secondary: const Color(0xFFD4843A),
    onSecondary: const Color(0xFFFFFFFF),
    secondaryContainer: const Color(0xFFFFF0DE),
    onSecondaryContainer: const Color(0xFF2E1500),
    tertiary: const Color(0xFFAD6420),
    onTertiary: const Color(0xFFFFFFFF),
    tertiaryContainer: const Color(0xFFEFB870),
    onTertiaryContainer: const Color(0xFF3A1800),
    surface: const Color(0xFFFFFFFF),
    onSurface: const Color(0xFF2E1500),
    surfaceContainerLowest: const Color(0xFFFFFFFF),
    surfaceContainerLow: const Color(0xFFFFF8F2),
    surfaceContainer: const Color(0xFFFFF3E8),
    surfaceContainerHigh: const Color(0xFFFFF0E2),
    surfaceContainerHighest: const Color(0xFFFFF0DE),
    onSurfaceVariant: const Color(0xFF6B3A00),
    outline: const Color(0xFFAD6420),
    outlineVariant: const Color(0xFFEFCFA0),
    inverseSurface: const Color(0xFF3D1E00),
    onInverseSurface: const Color(0xFFFFF8F2),
    inversePrimary: const Color(0xFFFFB366),
    surfaceTint: const Color(0xFFB85C00),
  ),
);

final _amberDark = _scheme(
  Brightness.dark,
  (
    primary: const Color(0xFFFFB366),
    onPrimary: const Color(0xFF4A2200),
    primaryContainer: const Color(0xFFB85C00),
    onPrimaryContainer: const Color(0xFFFFDCB4),
    secondary: const Color(0xFFEFCA90),
    onSecondary: const Color(0xFF4A2200),
    secondaryContainer: const Color(0xFF3D1E00),
    onSecondaryContainer: const Color(0xFFFFE5C8),
    tertiary: const Color(0xFFFFB366),
    onTertiary: const Color(0xFF4A2200),
    tertiaryContainer: const Color(0xFF3D1E00),
    onTertiaryContainer: const Color(0xFFFFDCB4),
    surface: const Color(0xFF2E1500),
    onSurface: const Color(0xFFFFE5C8),
    surfaceContainerLowest: const Color(0xFF1F0E00),
    surfaceContainerLow: const Color(0xFF2E1500),
    surfaceContainer: const Color(0xFF361900),
    surfaceContainerHigh: const Color(0xFF3D1E00),
    surfaceContainerHighest: const Color(0xFF4A2400),
    onSurfaceVariant: const Color(0xFFEFCA90),
    outline: const Color(0xFFAD6420),
    outlineVariant: const Color(0xFF8A4200),
    inverseSurface: const Color(0xFFFFE5C8),
    onInverseSurface: const Color(0xFF2E1500),
    inversePrimary: const Color(0xFFB85C00),
    surfaceTint: const Color(0xFFFFB366),
  ),
);

ThemeData _amoledTheme() => ThemeData(
      useMaterial3: true,
      scaffoldBackgroundColor: Colors.black,
      colorScheme: _scheme(
        Brightness.dark,
        (
          primary: const Color(0xFFE0E0E0),
          onPrimary: const Color(0xFF000000),
          primaryContainer: const Color(0xFF242424),
          onPrimaryContainer: const Color(0xFFFFFFFF),
          secondary: const Color(0xFF9E9E9E),
          onSecondary: const Color(0xFF000000),
          secondaryContainer: const Color(0xFF1A1A1A),
          onSecondaryContainer: const Color(0xFFE0E0E0),
          tertiary: const Color(0xFF757575),
          onTertiary: const Color(0xFFFFFFFF),
          tertiaryContainer: const Color(0xFF141414),
          onTertiaryContainer: const Color(0xFFE0E0E0),
          surface: const Color(0xFF0A0A0A),
          onSurface: const Color(0xFFE0E0E0),
          surfaceContainerLowest: const Color(0xFF000000),
          surfaceContainerLow: const Color(0xFF0A0A0A),
          surfaceContainer: const Color(0xFF111111),
          surfaceContainerHigh: const Color(0xFF1A1A1A),
          surfaceContainerHighest: const Color(0xFF242424),
          onSurfaceVariant: const Color(0xFF9E9E9E),
          outline: const Color(0xFF424242),
          outlineVariant: const Color(0xFF212121),
          inverseSurface: const Color(0xFFE0E0E0),
          onInverseSurface: const Color(0xFF000000),
          inversePrimary: const Color(0xFF424242),
          surfaceTint: const Color(0xFFE0E0E0),
        ),
        errorColors: (
          error: const Color(0xFFCF6679),
          onError: const Color(0xFFFFFFFF),
          errorContainer: const Color(0xFF93000A),
          onErrorContainer: const Color(0xFFFFDAD6),
        ),
      ),
    );
