sonar.projectKey=daypilot-test_daypilot-flutter
sonar.organization=daypilot-test
sonar.host.url=https://sonarcloud.io

sonar.sources=lib
sonar.tests=test
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=lib/l10n/**
sonar.coverage.exclusions=lib/screens/**,**/*_screen.dart,lib/components/**,lib/theme/**,lib/data/**,lib/core/window/**
sonar.cpd.exclusions=lib/theme/app_theme.dart
