package com.example.daypilot_test_desing.ui.theme

import androidx.compose.ui.graphics.Color

// ─── VERDE SALVIA ───────────────────────────────────────────────
val SageGreen_Primary       = Color(0xFF4A7C59)
val SageGreen_PrimaryVar    = Color(0xFF2E5E40)
val SageGreen_Secondary     = Color(0xFF81A88D)
val SageGreen_SecondaryVar  = Color(0xFF5C8A6A)
val SageGreen_Tertiary      = Color(0xFFA8C5A0)
val SageGreen_Background    = Color(0xFFF4F9F5)
val SageGreen_Surface       = Color(0xFFFFFFFF)
val SageGreen_SurfaceVar    = Color(0xFFE8F2EB)
val SageGreen_Error         = Color(0xFFBA1A1A)
val SageGreen_ErrorContainer= Color(0xFFFFDAD6)
val SageGreen_OnPrimary     = Color(0xFFFFFFFF)
val SageGreen_OnSecondary   = Color(0xFFFFFFFF)
val SageGreen_OnTertiary    = Color(0xFF1A3320)
val SageGreen_OnBackground  = Color(0xFF1A2E1F)
val SageGreen_OnSurface     = Color(0xFF1A2E1F)
val SageGreen_OnSurfaceVar  = Color(0xFF3D5C45)
val SageGreen_OnError       = Color(0xFFFFFFFF)
val SageGreen_Outline       = Color(0xFF6B9474)
val SageGreen_OutlineVar    = Color(0xFFB0CCB5)

// Dark variant
val SageGreenDark_Primary      = Color(0xFF7EBD8F)
val SageGreenDark_PrimaryVar   = Color(0xFF4A7C59)
val SageGreenDark_Secondary    = Color(0xFF9DBFA8)
val SageGreenDark_SecondaryVar = Color(0xFF5C8A6A)
val SageGreenDark_Tertiary     = Color(0xFF7EBD8F)
val SageGreenDark_Background   = Color(0xFF0E1F13)
val SageGreenDark_Surface      = Color(0xFF1A2E1F)
val SageGreenDark_SurfaceVar   = Color(0xFF243B29)
val SageGreenDark_Error        = Color(0xFFFFB4AB)
val SageGreenDark_ErrorContainer=Color(0xFF93000A)
val SageGreenDark_OnPrimary    = Color(0xFF0E3320)
val SageGreenDark_OnSecondary  = Color(0xFF1A3325)
val SageGreenDark_OnTertiary   = Color(0xFF0E3320)
val SageGreenDark_OnBackground = Color(0xFFD4EDDA)
val SageGreenDark_OnSurface    = Color(0xFFD4EDDA)
val SageGreenDark_OnSurfaceVar = Color(0xFF9DBFA8)
val SageGreenDark_OnError      = Color(0xFF690005)
val SageGreenDark_Outline      = Color(0xFF5C8A6A)
val SageGreenDark_OutlineVar   = Color(0xFF2E5E40)

// ─── AZUL OCÉANO ────────────────────────────────────────────────
val Ocean_Primary       = Color(0xFF1A6B8A)
val Ocean_PrimaryVar    = Color(0xFF0D4F6B)
val Ocean_Secondary     = Color(0xFF4A9BB5)
val Ocean_SecondaryVar  = Color(0xFF2E7A96)
val Ocean_Tertiary      = Color(0xFF80C4D8)
val Ocean_Background    = Color(0xFFF2F8FB)
val Ocean_Surface       = Color(0xFFFFFFFF)
val Ocean_SurfaceVar    = Color(0xFFE0F2F8)
val Ocean_Error         = Color(0xFFBA1A1A)
val Ocean_ErrorContainer= Color(0xFFFFDAD6)
val Ocean_OnPrimary     = Color(0xFFFFFFFF)
val Ocean_OnSecondary   = Color(0xFFFFFFFF)
val Ocean_OnTertiary    = Color(0xFF002B38)
val Ocean_OnBackground  = Color(0xFF001F2A)
val Ocean_OnSurface     = Color(0xFF001F2A)
val Ocean_OnSurfaceVar  = Color(0xFF1A4D5E)
val Ocean_OnError       = Color(0xFFFFFFFF)
val Ocean_Outline       = Color(0xFF4A8BA0)
val Ocean_OutlineVar    = Color(0xFFB0D8E8)

// Dark variant
val OceanDark_Primary      = Color(0xFF5BC8E8)
val OceanDark_PrimaryVar   = Color(0xFF1A6B8A)
val OceanDark_Secondary    = Color(0xFF80C4D8)
val OceanDark_SecondaryVar = Color(0xFF2E7A96)
val OceanDark_Tertiary     = Color(0xFF5BC8E8)
val OceanDark_Background   = Color(0xFF001F2A)
val OceanDark_Surface      = Color(0xFF002B38)
val OceanDark_SurfaceVar   = Color(0xFF0D3D4F)
val OceanDark_Error        = Color(0xFFFFB4AB)
val OceanDark_ErrorContainer=Color(0xFF93000A)
val OceanDark_OnPrimary    = Color(0xFF003547)
val OceanDark_OnSecondary  = Color(0xFF003547)
val OceanDark_OnTertiary   = Color(0xFF003547)
val OceanDark_OnBackground = Color(0xFFCCEAF5)
val OceanDark_OnSurface    = Color(0xFFCCEAF5)
val OceanDark_OnSurfaceVar = Color(0xFF80C4D8)
val OceanDark_OnError      = Color(0xFF690005)
val OceanDark_Outline      = Color(0xFF2E7A96)
val OceanDark_OutlineVar   = Color(0xFF0D4F6B)

// ─── MORADO LAVANDA ─────────────────────────────────────────────
val Lavender_Primary       = Color(0xFF6B4FA8)
val Lavender_PrimaryVar    = Color(0xFF4D338A)
val Lavender_Secondary     = Color(0xFF9B7FCC)
val Lavender_SecondaryVar  = Color(0xFF7A5EAD)
val Lavender_Tertiary      = Color(0xFFC4AAEE)
val Lavender_Background    = Color(0xFFF7F4FC)
val Lavender_Surface       = Color(0xFFFFFFFF)
val Lavender_SurfaceVar    = Color(0xFFEDE8F8)
val Lavender_Error         = Color(0xFFBA1A1A)
val Lavender_ErrorContainer= Color(0xFFFFDAD6)
val Lavender_OnPrimary     = Color(0xFFFFFFFF)
val Lavender_OnSecondary   = Color(0xFFFFFFFF)
val Lavender_OnTertiary    = Color(0xFF1E0A40)
val Lavender_OnBackground  = Color(0xFF1A1030)
val Lavender_OnSurface     = Color(0xFF1A1030)
val Lavender_OnSurfaceVar  = Color(0xFF4D338A)
val Lavender_OnError       = Color(0xFFFFFFFF)
val Lavender_Outline       = Color(0xFF7A5EAD)
val Lavender_OutlineVar    = Color(0xFFCFC0F0)

// Dark variant
val LavenderDark_Primary      = Color(0xFFBCA0E8)
val LavenderDark_PrimaryVar   = Color(0xFF6B4FA8)
val LavenderDark_Secondary    = Color(0xFFCDB8F0)
val LavenderDark_SecondaryVar = Color(0xFF7A5EAD)
val LavenderDark_Tertiary     = Color(0xFFBCA0E8)
val LavenderDark_Background   = Color(0xFF100A20)
val LavenderDark_Surface      = Color(0xFF1A1030)
val LavenderDark_SurfaceVar   = Color(0xFF261A40)
val LavenderDark_Error        = Color(0xFFFFB4AB)
val LavenderDark_ErrorContainer=Color(0xFF93000A)
val LavenderDark_OnPrimary    = Color(0xFF2B1060)
val LavenderDark_OnSecondary  = Color(0xFF2B1060)
val LavenderDark_OnTertiary   = Color(0xFF2B1060)
val LavenderDark_OnBackground = Color(0xFFE8DCFF)
val LavenderDark_OnSurface    = Color(0xFFE8DCFF)
val LavenderDark_OnSurfaceVar = Color(0xFFCDB8F0)
val LavenderDark_OnError      = Color(0xFF690005)
val LavenderDark_Outline      = Color(0xFF7A5EAD)
val LavenderDark_OutlineVar   = Color(0xFF4D338A)

// ─── NARANJA ÁMBAR ──────────────────────────────────────────────
val Amber_Primary       = Color(0xFFB85C00)
val Amber_PrimaryVar    = Color(0xFF8A4200)
val Amber_Secondary     = Color(0xFFD4843A)
val Amber_SecondaryVar  = Color(0xFFAD6420)
val Amber_Tertiary      = Color(0xFFEFB870)
val Amber_Background    = Color(0xFFFFF8F2)
val Amber_Surface       = Color(0xFFFFFFFF)
val Amber_SurfaceVar    = Color(0xFFFFF0DE)
val Amber_Error         = Color(0xFFBA1A1A)
val Amber_ErrorContainer= Color(0xFFFFDAD6)
val Amber_OnPrimary     = Color(0xFFFFFFFF)
val Amber_OnSecondary   = Color(0xFFFFFFFF)
val Amber_OnTertiary    = Color(0xFF3A1800)
val Amber_OnBackground  = Color(0xFF2E1500)
val Amber_OnSurface     = Color(0xFF2E1500)
val Amber_OnSurfaceVar  = Color(0xFF6B3A00)
val Amber_OnError       = Color(0xFFFFFFFF)
val Amber_Outline       = Color(0xFFAD6420)
val Amber_OutlineVar    = Color(0xFFEFCFA0)

// Dark variant
val AmberDark_Primary      = Color(0xFFFFB366)
val AmberDark_PrimaryVar   = Color(0xFFB85C00)
val AmberDark_Secondary    = Color(0xFFEFCA90)
val AmberDark_SecondaryVar = Color(0xFFAD6420)
val AmberDark_Tertiary     = Color(0xFFFFB366)
val AmberDark_Background   = Color(0xFF1F0E00)
val AmberDark_Surface      = Color(0xFF2E1500)
val AmberDark_SurfaceVar   = Color(0xFF3D1E00)
val AmberDark_Error        = Color(0xFFFFB4AB)
val AmberDark_ErrorContainer=Color(0xFF93000A)
val AmberDark_OnPrimary    = Color(0xFF4A2200)
val AmberDark_OnSecondary  = Color(0xFF4A2200)
val AmberDark_OnTertiary   = Color(0xFF4A2200)
val AmberDark_OnBackground = Color(0xFFFFE5C8)
val AmberDark_OnSurface    = Color(0xFFFFE5C8)
val AmberDark_OnSurfaceVar = Color(0xFFEFCA90)
val AmberDark_OnError      = Color(0xFF690005)
val AmberDark_Outline      = Color(0xFFAD6420)
val AmberDark_OutlineVar   = Color(0xFF8A4200)

// ─── OSCURO PURO ────────────────────────────────────────────────
val Amoled_Primary       = Color(0xFFE0E0E0)
val Amoled_PrimaryVar    = Color(0xFFBDBDBD)
val Amoled_Secondary     = Color(0xFF9E9E9E)
val Amoled_SecondaryVar  = Color(0xFF757575)
val Amoled_Tertiary      = Color(0xFF616161)
val Amoled_Background    = Color(0xFF000000)
val Amoled_Surface       = Color(0xFF0A0A0A)
val Amoled_SurfaceVar    = Color(0xFF141414)
val Amoled_Error         = Color(0xFFCF6679)
val Amoled_ErrorContainer= Color(0xFF93000A)
val Amoled_OnPrimary     = Color(0xFF000000)
val Amoled_OnSecondary   = Color(0xFF000000)
val Amoled_OnTertiary    = Color(0xFFFFFFFF)
val Amoled_OnBackground  = Color(0xFFE0E0E0)
val Amoled_OnSurface     = Color(0xFFE0E0E0)
val Amoled_OnSurfaceVar  = Color(0xFF9E9E9E)
val Amoled_OnError       = Color(0xFFFFFFFF)
val Amoled_Outline       = Color(0xFF424242)
val Amoled_OutlineVar    = Color(0xFF212121)